-- Installation de l'entrepôt : à exécuter une fois, avec ACCOUNTADMIN.
-- Rejouable : chaque instruction utilise IF NOT EXISTS.
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_TAXI
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;

CREATE ROLE IF NOT EXISTS ROLE_TAXI_TOOLS;

GRANT USAGE, OPERATE ON WAREHOUSE WH_TAXI TO ROLE ROLE_TAXI_TOOLS;
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE ROLE_TAXI_TOOLS;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA NYC_TAXI.RAW TO ROLE ROLE_TAXI_TOOLS;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.STAGING TO ROLE ROLE_TAXI_TOOLS;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE ROLE_TAXI_TOOLS;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.MARTS TO ROLE ROLE_TAXI_TOOLS;

CREATE USER IF NOT EXISTS SVC_TAXI_PIPELINE
  TYPE = SERVICE
  DEFAULT_ROLE = ROLE_TAXI_TOOLS
  DEFAULT_WAREHOUSE = WH_TAXI;
GRANT ROLE ROLE_TAXI_TOOLS TO USER SVC_TAXI_PIPELINE;

-- La clé publique s'enregistre à part, elle n'est pas versionnée :
-- ALTER USER SVC_TAXI_PIPELINE SET RSA_PUBLIC_KEY = '<clé publique>';
